<a href="https://colab.research.google.com/github/McKendreevv/Mis433/blob/main/MVV_data_manipuation_flights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation in Pandas

In this assignment, you will be working on the same dataframe of flights departing New York City in 2013.

In [2]:
pip install nycflights13

Collecting nycflights13
  Downloading nycflights13-0.0.3.tar.gz (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 48.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)
Building wheels for collected packages: nycflights13
  Building wheel for nycflights13 (setup.py) ... done
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732722 sha256=cbf94b2e14b43f71f48cb8e1e447278da67d327fb271d0d4aebc6071f6893508
  Stored in directory: /root/.cache/pip/wheels/58/ee/20/7838832df5510701439239ec10c2d8927de32aac2729ce2085
Successfully built nycflights13
Installing collected packages: nycflights13
Successfully installed nycflights13-0.0.3

In [1]:
import pandas as pd

In [3]:
# Install the package 'nycflights13' before you can run this
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [4]:
flights.shape

(336776, 19)

## Data frame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [5]:
# use describe() to summarize all columns
flights.describe(include='all')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,336776.000000,334264,336776,336776,327346.000000,336776.000000,336776.000000,336776.000000,336776
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,4043,3,105,NaN,NaN,NaN,NaN,6936
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,NaN,N725MQ,EWR,ORD,NaN,NaN,NaN,NaN,2013-09-13T12:00:00Z
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,NaN,575,120835,17283,NaN,NaN,NaN,NaN,94
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,1971.923620,NaN,NaN,NaN,150.686460,1039.912604,13.180247,26.230100,NaN
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,1632.471938,NaN,NaN,NaN,93.688305,733.233033,4.661316,19.300846,NaN
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,1.000000,NaN,NaN,NaN,20.000000,17.000000,1.000000,0.000000,NaN
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,553.000000,NaN,NaN,NaN,82.000000,502.000000,9.000000,8.000000,NaN
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,1496.000000,NaN,NaN,NaN,129.000000,872.000000,13.000000,29.000000,NaN
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,3465.000000,NaN,NaN,NaN,192.000000,1389.000000,17.000000,44.000000,NaN
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,8500.000000,NaN,NaN,NaN,695.000000,4983.000000,23.000000,59.000000,NaN

## Question 1. Selecting rows

From the 'flights' dataframe, find all flights that satisfy the following certain conditions:

In [6]:
# Had an arrival delay of two or more hours
print(flights[flights['arr_delay'] >= 120])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
119     2013      1    1     811.0             630      101.0    1047.0
151     2013      1    1     848.0            1835      853.0    1001.0
218     2013      1    1     957.0             733      144.0    1056.0
268     2013      1    1    1114.0             900      134.0    1447.0
447     2013      1    1    1505.0            1310      115.0    1638.0
...      ...    ...  ...       ...             ...        ...       ...
336579  2013      9   30    1823.0            1545      158.0    1934.0
336668  2013      9   30    1951.0            1649      182.0    2157.0
336724  2013      9   30    2053.0            1815      158.0    2310.0
336757  2013      9   30    2159.0            1845      194.0    2344.0
336763  2013      9   30    2235.0            2001      154.0      59.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
119                830      137.0      MQ    4576  N531MQ    LGA  CLT
151               1950      851.0      MQ    3944  N942MQ    JFK  BWI
218                853      123.0      UA     856  N534UA    EWR  BOS
268               1222      145.0      UA    1086  N76502    LGA  IAH
447               1431      127.0      EV    4497  N17984    EWR  RIC
...                ...        ...     ...     ...     ...    ...  ...
336579            1733      121.0      9E    3459  N916XJ    JFK  BNA
336668            1903      174.0      EV    4294  N13988    EWR  SAV
336724            2054      136.0      EV    5292  N600QX    EWR  ATL
336757            2030      194.0      9E    3320  N906XJ    JFK  BUF
336763            2249      130.0      B6    1083  N804JB    JFK  MCO

        air_time  distance  hour  minute             time_hour
119        118.0       544     6      30  2013-01-01T11:00:00Z
151         41.0       184    18      35  2013-01-01T23:00:00Z
218         37.0       200     7      33  2013-01-01T12:00:00Z
268        248.0      1416     9       0  2013-01-01T14:00:00Z
447         63.0       277    13      10  2013-01-01T18:00:00Z
...          ...       ...   ...     ...                   ...
336579      95.0       765    15      45  2013-09-30T19:00:00Z
336668      95.0       708    16      49  2013-09-30T20:00:00Z
336724      91.0       746    18      15  2013-09-30T22:00:00Z
336757      50.0       301    18      45  2013-09-30T22:00:00Z
336763     123.0       944    20       1  2013-10-01T00:00:00Z

[10200 rows x 19 columns]

In [7]:
# Flew to Houston (IAH or HOU)
print(flights[(flights['dest'] == 'IAH') | (flights['dest'] == 'HOU')])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0       2013      1    1     517.0             515        2.0     830.0
1       2013      1    1     533.0             529        4.0     850.0
32      2013      1    1     623.0             627       -4.0     933.0
81      2013      1    1     728.0             732       -4.0    1041.0
89      2013      1    1     739.0             739        0.0    1104.0
...      ...    ...  ...       ...             ...        ...       ...
336524  2013      9   30    1729.0            1720        9.0    2001.0
336527  2013      9   30    1735.0            1715       20.0    2010.0
336618  2013      9   30    1859.0            1859        0.0    2134.0
336694  2013      9   30    2015.0            2015        0.0    2244.0
336737  2013      9   30    2105.0            2106       -1.0    2329.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
0                  819       11.0      UA    1545  N14228    EWR  IAH
1                  830       20.0      UA    1714  N24211    LGA  IAH
32                 932        1.0      UA     496  N459UA    LGA  IAH
81                1038        3.0      UA     473  N488UA    LGA  IAH
89                1038       26.0      UA    1479  N37408    EWR  IAH
...                ...        ...     ...     ...     ...    ...  ...
336524            2010       -9.0      UA     652  N455UA    EWR  IAH
336527            2005        5.0      WN    2067  N296WN    EWR  HOU
336618            2159      -25.0      UA    1128  N14731    LGA  IAH
336694            2307      -23.0      UA    1545  N17730    EWR  IAH
336737            2354      -25.0      UA     475  N477UA    EWR  IAH

        air_time  distance  hour  minute             time_hour
0          227.0      1400     5      15  2013-01-01T10:00:00Z
1          227.0      1416     5      29  2013-01-01T10:00:00Z
32         229.0      1416     6      27  2013-01-01T11:00:00Z
81         238.0      1416     7      32  2013-01-01T12:00:00Z
89         249.0      1400     7      39  2013-01-01T12:00:00Z
...          ...       ...   ...     ...                   ...
336524     173.0      1400    17      20  2013-09-30T21:00:00Z
336527     188.0      1411    17      15  2013-09-30T21:00:00Z
336618     180.0      1416    18      59  2013-09-30T22:00:00Z
336694     174.0      1400    20      15  2013-10-01T00:00:00Z
336737     175.0      1400    21       6  2013-10-01T01:00:00Z

[9313 rows x 19 columns]

In [8]:
# Were operated by United (UA), American (AA), or Delta (DL)
print(flights[(flights['carrier'] == 'UA') | (flights['carrier'] == 'AA') | (flights['carrier'] == 'DL')])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0       2013      1    1     517.0             515        2.0     830.0
1       2013      1    1     533.0             529        4.0     850.0
2       2013      1    1     542.0             540        2.0     923.0
4       2013      1    1     554.0             600       -6.0     812.0
5       2013      1    1     554.0             558       -4.0     740.0
...      ...    ...  ...       ...             ...        ...       ...
336737  2013      9   30    2105.0            2106       -1.0    2329.0
336744  2013      9   30    2121.0            2100       21.0    2349.0
336751  2013      9   30    2140.0            2140        0.0      10.0
336755  2013      9   30    2149.0            2156       -7.0    2245.0
336762  2013      9   30    2233.0            2113       80.0     112.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
0                  819       11.0      UA    1545  N14228    EWR  IAH
1                  830       20.0      UA    1714  N24211    LGA  IAH
2                  850       33.0      AA    1141  N619AA    JFK  MIA
4                  837      -25.0      DL     461  N668DN    LGA  ATL
5                  728       12.0      UA    1696  N39463    EWR  ORD
...                ...        ...     ...     ...     ...    ...  ...
336737            2354      -25.0      UA     475  N477UA    EWR  IAH
336744              14      -25.0      DL    2363  N193DN    JFK  LAX
336751              40      -30.0      AA     185  N335AA    JFK  LAX
336755            2308      -23.0      UA     523  N813UA    EWR  BOS
336762              30       42.0      UA     471  N578UA    EWR  SFO

        air_time  distance  hour  minute             time_hour
0          227.0      1400     5      15  2013-01-01T10:00:00Z
1          227.0      1416     5      29  2013-01-01T10:00:00Z
2          160.0      1089     5      40  2013-01-01T10:00:00Z
4          116.0       762     6       0  2013-01-01T11:00:00Z
5          150.0       719     5      58  2013-01-01T10:00:00Z
...          ...       ...   ...     ...                   ...
336737     175.0      1400    21       6  2013-10-01T01:00:00Z
336744     296.0      2475    21       0  2013-10-01T01:00:00Z
336751     298.0      2475    21      40  2013-10-01T01:00:00Z
336755      37.0       200    21      56  2013-10-01T01:00:00Z
336762     318.0      2565    21      13  2013-10-01T01:00:00Z

[139504 rows x 19 columns]

In [9]:
# Departed in July, August, and September
print(flights[(flights['month'] == 7) | (flights['month'] == 8) | (flights['month'] == 9)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
250450  2013      7    1       1.0            2029      212.0     236.0
250451  2013      7    1       2.0            2359        3.0     344.0
250452  2013      7    1      29.0            2245      104.0     151.0
250453  2013      7    1      43.0            2130      193.0     322.0
250454  2013      7    1      44.0            2150      174.0     300.0
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
250450            2359      157.0      B6     915  N653JB    JFK  SFO
250451             344        0.0      B6    1503  N805JB    JFK  SJU
250452               1      110.0      B6     234  N348JB    JFK  BTV
250453              14      188.0      B6    1371  N794JB    LGA  FLL
250454             100      120.0      AA     185  N324AA    JFK  LAX
...                ...        ...     ...     ...     ...    ...  ...
336771            1634        NaN      9E    3393     NaN    JFK  DCA
336772            2312        NaN      9E    3525     NaN    LGA  SYR
336773            1330        NaN      MQ    3461  N535MQ    LGA  BNA
336774            1344        NaN      MQ    3572  N511MQ    LGA  CLE
336775            1020        NaN      MQ    3531  N839MQ    LGA  RDU

        air_time  distance  hour  minute             time_hour
250450     315.0      2586    20      29  2013-07-02T00:00:00Z
250451     200.0      1598    23      59  2013-07-02T03:00:00Z
250452      66.0       266    22      45  2013-07-02T02:00:00Z
250453     143.0      1076    21      30  2013-07-02T01:00:00Z
250454     297.0      2475    21      50  2013-07-02T01:00:00Z
...          ...       ...   ...     ...                   ...
336771       NaN       213    14      55  2013-09-30T18:00:00Z
336772       NaN       198    22       0  2013-10-01T02:00:00Z
336773       NaN       764    12      10  2013-09-30T16:00:00Z
336774       NaN       419    11      59  2013-09-30T15:00:00Z
336775       NaN       431     8      40  2013-09-30T12:00:00Z

[86326 rows x 19 columns]

In [10]:
# Arrived more than two hours late, but didn’t leave late
print(flights[(flights['arr_delay'] > 120) & (flights['dep_delay'] <= 0)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
22911   2013      1   27    1419.0            1420       -1.0    1754.0
33011   2013     10    7    1350.0            1350        0.0    1736.0
33019   2013     10    7    1357.0            1359       -2.0    1858.0
41075   2013     10   16     657.0             700       -3.0    1258.0
55985   2013     11    1     658.0             700       -2.0    1329.0
152766  2013      3   18    1844.0            1847       -3.0      39.0
180893  2013      4   17    1635.0            1640       -5.0    2049.0
181270  2013      4   18     558.0             600       -2.0    1149.0
181327  2013      4   18     655.0             700       -5.0    1213.0
213693  2013      5   22    1827.0            1830       -3.0    2217.0
214512  2013      5   23    1810.0            1810        0.0    2208.0
226434  2013      6    5    1604.0            1615      -11.0    2041.0
235033  2013      6   14    1708.0            1710       -2.0    2227.0
244329  2013      6   24    1602.0            1605       -3.0    2134.0
247568  2013      6   27    2052.0            2100       -8.0      13.0
249957  2013      6   30    1423.0            1425       -2.0    1816.0
250689  2013      7    1     905.0             905        0.0    1443.0
256340  2013      7    7    1659.0            1700       -1.0    2050.0
256358  2013      7    7    1727.0            1730       -3.0    2203.0
256373  2013      7    7    1746.0            1755       -9.0    2133.0
256405  2013      7    7    1823.0            1830       -7.0    2201.0
270742  2013      7   22    1555.0            1600       -5.0    2139.0
270752  2013      7   22    1606.0            1615       -9.0    2056.0
270762  2013      7   22    1628.0            1630       -2.0    2151.0
276564  2013      7   28    1710.0            1711       -1.0    2248.0
287148  2013      8    8    1457.0            1500       -3.0    1828.0
291439  2013      8   13     657.0             659       -2.0    1015.0
305985  2013      8   28    1157.0            1200       -3.0    1520.0
325764  2013      9   19     656.0             700       -4.0    1037.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
22911             1550      124.0      MQ    3728  N1EAMQ    EWR  ORD
33011             1526      130.0      EV    5181  N611QX    LGA  MSN
33019             1654      124.0      AA    1151  N3CMAA    LGA  DFW
41075             1056      122.0      B6       3  N703JB    JFK  SJU
55985             1015      194.0      VX     399  N629VA    JFK  LAX
152766            2219      140.0      UA     389  N560UA    JFK  SFO
180893            1845      124.0      MQ    4540  N721MQ    LGA  DTW
181270             850      179.0      AA     707  N3EXAA    LGA  DFW
181327             950      143.0      AA    2083  N565AA    EWR  DFW
213693            2010      127.0      MQ    4674  N518MQ    LGA  CLE
214512            2000      128.0      MQ    4626  N525MQ    LGA  CMH
226434            1840      121.0      MQ    4657  N510MQ    LGA  ATL
235033            2015      132.0      AA     181  N320AA    JFK  LAX
244329            1916      138.0      DL     706   N3768    JFK  AUS
247568            2210      123.0      US    2144  N952UW    LGA  BOS
249957            1554      142.0      B6    2402  N206JB    JFK  BUF
250689            1223      140.0      DL    1057  N337NB    LGA  MIA
256340            1823      147.0      US    2183  N948UW    LGA  DCA
256358            1951      132.0      F9     837  N263AV    LGA  DEN
256373            1921      132.0      B6    1407  N374JB    JFK  IAD
256405            1955      126.0      MQ    3486  N724MQ    LGA  BNA
270742            1938      121.0      DL     141  N713TW    JFK  SFO
270752            1831      145.0      DL    1619  N970DL    LGA  MSP
270762            1939      132.0      B6     423  N625JB    JFK  LAX
276564            2039      129.0      B6     167  N510JB    JFK  OAK
287148            1624      124.0      US    2185  N746UW    LGA  DCA
291439             814      121.0      EV    4522  N14188    EWR  BNA
305985            1316      124.0      US    2179  N737US    LGA  DCA
325764             833      124.0      UA     331  N808UA    LGA  ORD

        air_time  distance  hour  minute             time_hour
22911      135.0       719    14      20  2013-01-27T19:00:00Z
33011      117.0       812    13      50  2013-10-07T17:00:00Z
33019      192.0      1389    13      59  2013-10-07T17:00:00Z
41075      225.0      1598     7       0  2013-10-16T11:00:00Z
55985      336.0      2475     7       0  2013-11-01T11:00:00Z
152766     386.0      2586    18      47  2013-03-18T22:00:00Z
180893     130.0       502    16      40  2013-04-17T20:00:00Z
181270     234.0      1389     6       0  2013-04-18T10:00:00Z
181327     230.0      1372     7       0  2013-04-18T11:00:00Z
213693      90.0       419    18      30  2013-05-22T22:00:00Z
214512      82.0       479    18      10  2013-05-23T22:00:00Z
226434     158.0       762    16      15  2013-06-05T20:00:00Z
235033     334.0      2475    17      10  2013-06-14T21:00:00Z
244329     247.0      1521    16       5  2013-06-24T20:00:00Z
247568      46.0       184    21       0  2013-06-28T01:00:00Z
249957      80.0       301    14      25  2013-06-30T18:00:00Z
250689     183.0      1096     9       5  2013-07-01T13:00:00Z
256340      64.0       214    17       0  2013-07-07T21:00:00Z
256358     236.0      1620    17      30  2013-07-07T21:00:00Z
256373      78.0       228    17      55  2013-07-07T21:00:00Z
256405     113.0       764    18      30  2013-07-07T22:00:00Z
270742     371.0      2586    16       0  2013-07-22T20:00:00Z
270752     140.0      1020    16      15  2013-07-22T20:00:00Z
270762     332.0      2475    16      30  2013-07-22T20:00:00Z
276564     353.0      2576    17      11  2013-07-28T21:00:00Z
287148      70.0       214    15       0  2013-08-08T19:00:00Z
291439     146.0       748     6      59  2013-08-13T10:00:00Z
305985      63.0       214    12       0  2013-08-28T16:00:00Z
325764     192.0       733     7       0  2013-09-19T11:00:00Z

In [11]:
# Were delayed by at least an hour, but made up over 30 minutes in flight
print(flights[(flights['dep_delay'] >= 60) & (flights['arr_delay'] - flights['dep_delay'] > 30)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
119     2013      1    1     811.0             630      101.0    1047.0
395     2013      1    1    1400.0            1250       70.0    1645.0
498     2013      1    1    1549.0            1445       64.0    1912.0
609     2013      1    1    1732.0            1630       62.0    2028.0
639     2013      1    1    1803.0            1620      103.0    2008.0
...      ...    ...  ...       ...             ...        ...       ...
326075  2013      9   19    1213.0            1100       73.0    1456.0
326089  2013      9   19    1225.0            1000      145.0    1436.0
327051  2013      9   20    1150.0             955      115.0    1544.0
327450  2013      9   20    1811.0            1530      161.0    2203.0
328889  2013      9   22    1538.0            1340      118.0    1746.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
119                830      137.0      MQ    4576  N531MQ    LGA  CLT
395               1502      103.0      EV    4869  N748EV    LGA  MEM
498               1656      136.0      EV    4181  N21197    EWR  MCI
609               1825      123.0      EV    4092  N16911    EWR  DAY
639               1750      138.0      MQ    4622  N504MQ    LGA  BNA
...                ...        ...     ...     ...     ...    ...  ...
326075            1223      153.0      UA     798  N464UA    EWR  ORD
326089            1128      188.0      UA     775  N415UA    EWR  ORD
327051            1310      154.0      UA     642  N525UA    JFK  SFO
327450            1845      198.0      AA      85  N373AA    JFK  SFO
328889            1459      167.0      B6    2402  N258JB    JFK  BUF

        air_time  distance  hour  minute             time_hour
119        118.0       544     6      30  2013-01-01T11:00:00Z
395        178.0       963    12      50  2013-01-01T17:00:00Z
498        234.0      1092    14      45  2013-01-01T19:00:00Z
609        119.0       533    16      30  2013-01-01T21:00:00Z
639        154.0       764    16      20  2013-01-01T21:00:00Z
...          ...       ...   ...     ...                   ...
326075     105.0       719    11       0  2013-09-19T15:00:00Z
326089     104.0       719    10       0  2013-09-19T14:00:00Z
327051     346.0      2586     9      55  2013-09-20T13:00:00Z
327450     356.0      2586    15      30  2013-09-20T19:00:00Z
328889      59.0       301    13      40  2013-09-22T17:00:00Z

[1948 rows x 19 columns]

In [12]:
# Departed between midnight and 6am (inclusive)
print(flights[(flights['dep_time'] >= 0) & (flights['dep_time'] <= 600)])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0       2013      1    1     517.0             515        2.0     830.0
1       2013      1    1     533.0             529        4.0     850.0
2       2013      1    1     542.0             540        2.0     923.0
3       2013      1    1     544.0             545       -1.0    1004.0
4       2013      1    1     554.0             600       -6.0     812.0
...      ...    ...  ...       ...             ...        ...       ...
335802  2013      9   30     557.0             600       -3.0     852.0
335803  2013      9   30     558.0             600       -2.0     815.0
335804  2013      9   30     558.0             600       -2.0     742.0
335805  2013      9   30     559.0             600       -1.0       NaN
335806  2013      9   30     600.0             600        0.0     844.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
0                  819       11.0      UA    1545  N14228    EWR  IAH
1                  830       20.0      UA    1714  N24211    LGA  IAH
2                  850       33.0      AA    1141  N619AA    JFK  MIA
3                 1022      -18.0      B6     725  N804JB    JFK  BQN
4                  837      -25.0      DL     461  N668DN    LGA  ATL
...                ...        ...     ...     ...     ...    ...  ...
335802             923      -31.0      UA     303  N510UA    JFK  SFO
335803             829      -14.0      EV    4137  N16981    EWR  ATL
335804             749       -7.0      DL     731  N337NB    LGA  DTW
335805             715        NaN      WN     464  N411WN    EWR  MDW
335806             856      -12.0      B6     601  N588JB    JFK  FLL

        air_time  distance  hour  minute             time_hour
0          227.0      1400     5      15  2013-01-01T10:00:00Z
1          227.0      1416     5      29  2013-01-01T10:00:00Z
2          160.0      1089     5      40  2013-01-01T10:00:00Z
3          183.0      1576     5      45  2013-01-01T10:00:00Z
4          116.0       762     6       0  2013-01-01T11:00:00Z
...          ...       ...   ...     ...                   ...
335802     326.0      2586     6       0  2013-09-30T10:00:00Z
335803     107.0       746     6       0  2013-09-30T10:00:00Z
335804      83.0       502     6       0  2013-09-30T10:00:00Z
335805       NaN       711     6       0  2013-09-30T10:00:00Z
335806     139.0      1069     6       0  2013-09-30T10:00:00Z

[9344 rows x 19 columns]

In [13]:
# How many flights have a missing dep_time?
print(flights[flights['dep_time'].isnull()])

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
838     2013      1    1       NaN            1630        NaN       NaN
839     2013      1    1       NaN            1935        NaN       NaN
840     2013      1    1       NaN            1500        NaN       NaN
841     2013      1    1       NaN             600        NaN       NaN
1777    2013      1    2       NaN            1540        NaN       NaN
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
838               1815        NaN      EV    4308  N18120    EWR  RDU
839               2240        NaN      AA     791  N3EHAA    LGA  DFW
840               1825        NaN      AA    1925  N3EVAA    LGA  MIA
841                901        NaN      B6     125  N618JB    JFK  FLL
1777              1747        NaN      EV    4352  N10575    EWR  CVG
...                ...        ...     ...     ...     ...    ...  ...
336771            1634        NaN      9E    3393     NaN    JFK  DCA
336772            2312        NaN      9E    3525     NaN    LGA  SYR
336773            1330        NaN      MQ    3461  N535MQ    LGA  BNA
336774            1344        NaN      MQ    3572  N511MQ    LGA  CLE
336775            1020        NaN      MQ    3531  N839MQ    LGA  RDU

        air_time  distance  hour  minute             time_hour
838          NaN       416    16      30  2013-01-01T21:00:00Z
839          NaN      1389    19      35  2013-01-02T00:00:00Z
840          NaN      1096    15       0  2013-01-01T20:00:00Z
841          NaN      1069     6       0  2013-01-01T11:00:00Z
1777         NaN       569    15      40  2013-01-02T20:00:00Z
...          ...       ...   ...     ...                   ...
336771       NaN       213    14      55  2013-09-30T18:00:00Z
336772       NaN       198    22       0  2013-10-01T02:00:00Z
336773       NaN       764    12      10  2013-09-30T16:00:00Z
336774       NaN       419    11      59  2013-09-30T15:00:00Z
336775       NaN       431     8      40  2013-09-30T12:00:00Z

[8255 rows x 19 columns]

## Question 2. Sorting

In [14]:
# Sort flights to find the least delayed flights. Find the flights that left earliest.
print(flights.sort_values(by='dep_delay'))
print(flights.sort_values(by='dep_time'))

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
89673   2013     12    7    2040.0            2123      -43.0      40.0
113633  2013      2    3    2022.0            2055      -33.0    2240.0
64501   2013     11   10    1408.0            1440      -32.0    1549.0
9619    2013      1   11    1900.0            1930      -30.0    2233.0
24915   2013      1   29    1703.0            1730      -27.0    1947.0
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
89673             2352       48.0      B6      97  N592JB    JFK  DEN
113633            2338      -58.0      DL    1715  N612DL    LGA  MSY
64501             1559      -10.0      EV    5713  N825AS    LGA  IAD
9619              2243      -10.0      DL    1435  N934DL    LGA  TPA
24915             1957      -10.0      F9     837  N208FR    LGA  DEN
...                ...        ...     ...     ...     ...    ...  ...
336771            1634        NaN      9E    3393     NaN    JFK  DCA
336772            2312        NaN      9E    3525     NaN    LGA  SYR
336773            1330        NaN      MQ    3461  N535MQ    LGA  BNA
336774            1344        NaN      MQ    3572  N511MQ    LGA  CLE
336775            1020        NaN      MQ    3531  N839MQ    LGA  RDU

        air_time  distance  hour  minute             time_hour
89673      265.0      1626    21      23  2013-12-08T02:00:00Z
113633     162.0      1183    20      55  2013-02-04T01:00:00Z
64501       52.0       229    14      40  2013-11-10T19:00:00Z
9619       139.0      1010    19      30  2013-01-12T00:00:00Z
24915      250.0      1620    17      30  2013-01-29T22:00:00Z
...          ...       ...   ...     ...                   ...
336771       NaN       213    14      55  2013-09-30T18:00:00Z
336772       NaN       198    22       0  2013-10-01T02:00:00Z
336773       NaN       764    12      10  2013-09-30T16:00:00Z
336774       NaN       419    11      59  2013-09-30T15:00:00Z
336775       NaN       431     8      40  2013-09-30T12:00:00Z

[336776 rows x 19 columns]
        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
10452   2013      1   13       1.0            2249       72.0     108.0
100800  2013     12   20       1.0            2359        2.0     430.0
212954  2013      5   22       1.0            1935      266.0     154.0
297030  2013      8   19       1.0            2359        2.0     347.0
131559  2013      2   24       1.0            2245       76.0     121.0
...      ...    ...  ...       ...             ...        ...       ...
336771  2013      9   30       NaN            1455        NaN       NaN
336772  2013      9   30       NaN            2200        NaN       NaN
336773  2013      9   30       NaN            1210        NaN       NaN
336774  2013      9   30       NaN            1159        NaN       NaN
336775  2013      9   30       NaN             840        NaN       NaN

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
10452             2357       71.0      B6      22  N206JB    JFK  SYR
100800             440      -10.0      B6    1503  N608JB    JFK  SJU
212954            2140      254.0      EV    4361  N27200    EWR  TYS
297030             350       -3.0      B6     745  N552JB    JFK  PSE
131559            2354       87.0      B6     608  N216JB    JFK  PWM
...                ...        ...     ...     ...     ...    ...  ...
336771            1634        NaN      9E    3393     NaN    JFK  DCA
336772            2312        NaN      9E    3525     NaN    LGA  SYR
336773            1330        NaN      MQ    3461  N535MQ    LGA  BNA
336774            1344        NaN      MQ    3572  N511MQ    LGA  CLE
336775            1020        NaN      MQ    3531  N839MQ    LGA  RDU

        air_time  distance  hour  minute             time_hour
10452       41.0       209    22      49  2013-01-14T03:00:00Z
100800     182.0      1598    23      59  2013-12-21T04:00:00Z
212954      94.0       631    19      35  2013-05-22T23:00:00Z
297030     201.0      1617    23      59  2013-08-20T03:00:00Z
131559      56.0       273    22      45  2013-02-25T03:00:00Z
...          ...       ...   ...     ...                   ...
336771       NaN       213    14      55  2013-09-30T18:00:00Z
336772       NaN       198    22       0  2013-10-01T02:00:00Z
336773       NaN       764    12      10  2013-09-30T16:00:00Z
336774       NaN       419    11      59  2013-09-30T15:00:00Z
336775       NaN       431     8      40  2013-09-30T12:00:00Z

[336776 rows x 19 columns]

In [15]:
# Which flights travelled the farthest? Which travelled the shortest?
print(flights.sort_values(by='distance', ascending=False))
print(flights.sort_values(by='distance'))

        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
118311  2013      2    9    1206.0             900      186.0    1814.0
227103  2013      6    6    1044.0            1000       44.0    1441.0
224146  2013      6    3     957.0            1000       -3.0    1432.0
170226  2013      4    6     957.0            1000       -3.0    1510.0
130088  2013      2   22     857.0             900       -3.0    1436.0
...      ...    ...  ...       ...             ...        ...       ...
115505  2013      2    5    2136.0            2130        6.0    2238.0
25145   2013      1   29    2131.0            2130        1.0    2221.0
170692  2013      4    6    1948.0            1950       -2.0    2034.0
112694  2013      2    2    1610.0            1617       -7.0    1702.0
275945  2013      7   27       NaN             106        NaN       NaN

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
118311            1540      154.0      HA      51  N380HA    JFK  HNL
227103            1435        6.0      HA      51  N384HA    JFK  HNL
224146            1435       -3.0      HA      51  N381HA    JFK  HNL
170226            1510        0.0      HA      51  N382HA    JFK  HNL
130088            1540      -64.0      HA      51  N382HA    JFK  HNL
...                ...        ...     ...     ...     ...    ...  ...
115505            2225       13.0      EV    4619  N26141    EWR  PHL
25145             2225       -4.0      EV    4619  N13538    EWR  PHL
170692            2044      -10.0      EV    4457  N29917    EWR  PHL
112694            1722      -20.0      EV    4616  N18120    EWR  PHL
275945             245        NaN      US    1632     NaN    EWR  LGA

        air_time  distance  hour  minute             time_hour
118311     645.0      4983     9       0  2013-02-09T14:00:00Z
227103     580.0      4983    10       0  2013-06-06T14:00:00Z
224146     605.0      4983    10       0  2013-06-03T14:00:00Z
170226     638.0      4983    10       0  2013-04-06T14:00:00Z
130088     606.0      4983     9       0  2013-02-22T14:00:00Z
...          ...       ...   ...     ...                   ...
115505      31.0        80    21      30  2013-02-06T02:00:00Z
25145       25.0        80    21      30  2013-01-30T02:00:00Z
170692      25.0        80    19      50  2013-04-06T23:00:00Z
112694      33.0        80    16      17  2013-02-02T21:00:00Z
275945       NaN        17     1       6  2013-07-27T05:00:00Z

[336776 rows x 19 columns]
        year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
275945  2013      7   27       NaN             106        NaN       NaN
116412  2013      2    6    2125.0            2129       -4.0    2207.0
164109  2013      3   30    1942.0            1950       -8.0    2026.0
150994  2013      3   16    1947.0            1950       -3.0    2055.0
19088   2013      1   22    2203.0            2130       33.0    2317.0
...      ...    ...  ...       ...             ...        ...       ...
246012  2013      6   26     954.0            1000       -6.0    1421.0
5473    2013      1    7    1042.0             900      102.0    1620.0
47786   2013     10   23     952.0            1000       -8.0    1431.0
136482  2013      3    1     904.0             900        4.0    1438.0
111507  2013      2    1     855.0             900       -5.0    1442.0

        sched_arr_time  arr_delay carrier  flight tailnum origin dest  \
275945             245        NaN      US    1632     NaN    EWR  LGA
116412            2224      -17.0      EV    4619  N12564    EWR  PHL
164109            2044      -18.0      EV    4457  N12569    EWR  PHL
150994            2044       11.0      EV    4457  N48901    EWR  PHL
19088             2225       52.0      EV    4619  N13538    EWR  PHL
...                ...        ...     ...     ...     ...    ...  ...
246012            1435      -14.0      HA      51  N384HA    JFK  HNL
5473              1530       50.0      HA      51  N385HA    JFK  HNL
47786             1450      -19.0      HA      51  N393HA    JFK  HNL
136482            1540      -62.0      HA      51  N388HA    JFK  HNL
111507            1540      -58.0      HA      51  N388HA    JFK  HNL

        air_time  distance  hour  minute             time_hour
275945       NaN        17     1       6  2013-07-27T05:00:00Z
116412      28.0        80    21      29  2013-02-07T02:00:00Z
164109      24.0        80    19      50  2013-03-30T23:00:00Z
150994      31.0        80    19      50  2013-03-16T23:00:00Z
19088       31.0        80    21      30  2013-01-23T02:00:00Z
...          ...       ...   ...     ...                   ...
246012     601.0      4983    10       0  2013-06-26T14:00:00Z
5473       612.0      4983     9       0  2013-01-07T14:00:00Z
47786      619.0      4983    10       0  2013-10-23T14:00:00Z
136482     617.0      4983     9       0  2013-03-01T14:00:00Z
111507     620.0      4983     9       0  2013-02-01T14:00:00Z

[336776 rows x 19 columns]

## Question 3. Selecting Columns

Use at least three ways to select dep_time, dep_delay, arr_time, and arr_delay from flights.

In [16]:
# Method 1
print(flights[['dep_time', 'dep_delay', 'arr_time', 'arr_delay']])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [18]:
# Method 2
print(flights.loc[:, ['dep_time', 'dep_delay', 'arr_time', 'arr_delay']])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [19]:
# Method 3
print(flights.filter(items=['dep_time', 'dep_delay', 'arr_time', 'arr_delay']))

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

## Question 4. Adding new columns

Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers.

For example, 759 means 7:59 and 801 means 8:01. Their difference is not 42 but 2 minutes.

In [20]:
# Convert them to a more convenient representation of number of minutes since midnight (0).
print(flights['dep_time'].apply(lambda x: x % 100 + x // 100 * 60))

0         317.0
1         333.0
2         342.0
3         344.0
4         354.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: dep_time, Length: 336776, dtype: float64

In [21]:
# Create a new column of arr_time - dep_time.
print(flights['arr_time'] - flights['dep_time'])

# Compare this column with air_time.
print(flights['arr_time'] - flights['dep_time'] == flights['air_time'])

0         313.0
1         317.0
2         381.0
3         460.0
4         258.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Length: 336776, dtype: float64
0         False
1         False
2         False
3         False
4         False
          ...
336771    False
336772    False
336773    False
336774    False
336775    False
Length: 336776, dtype: bool

In [32]:
# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# Try creating a column to calculate dep_delay from dep_time and sched_dep_time (and/or other columns if necessary).
def hhmm_to_minutes(x):
    if pd.isna(x):
        return x
    hours = x // 100
    minutes = x % 100
    return hours * 60 + minutes
flights['dep_time_min'] = flights['dep_time'].apply(hhmm_to_minutes)
flights['sched_dep_time_min'] = flights['sched_dep_time'].apply(hhmm_to_minutes)

flights['calc_dep_delay'] = flights['dep_time_min'] - flights['sched_dep_time_min']
flights.loc[flights['calc_dep_delay'] < -720, 'calc_dep_delay'] += 1440

# Test your results.

print(flights['calc_dep_delay'] == flights['dep_delay'])

0          True
1          True
2          True
3          True
4          True
          ...
336771    False
336772    False
336773    False
336774    False
336775    False
Length: 336776, dtype: bool

## Question 5. Mixing things together

The following questions may require multiple operations above.

In [33]:
# Find the 20 most delayed flights.
# Display the following: year,month,day,carrier,flight,dep_delay,arr_delay,carrier
# How do you want to handle ties?
print(flights.sort_values(by='dep_delay', ascending=False)[
    ['year', 'month', 'day', 'carrier', 'flight', 'dep_delay', 'arr_delay']
].head(20))
#ties for the 20th place are ignored, If included the list could be more than 20 values

        year  month  day carrier  flight  dep_delay  arr_delay
7072    2013      1    9      HA      51     1301.0     1272.0
235778  2013      6   15      MQ    3535     1137.0     1127.0
8239    2013      1   10      MQ    3695     1126.0     1109.0
327043  2013      9   20      AA     177     1014.0     1007.0
270376  2013      7   22      MQ    3075     1005.0      989.0
173992  2013      4   10      DL    2391      960.0      931.0
151974  2013      3   17      DL    2119      911.0      915.0
247040  2013      6   27      DL    2007      899.0      850.0
270987  2013      7   22      DL    2047      898.0      895.0
87238   2013     12    5      AA     172      896.0      878.0
195711  2013      5    3      MQ    3744      878.0      875.0
151     2013      1    1      MQ    3944      853.0      851.0
210174  2013      5   19      AA     257      853.0      852.0
119784  2013      2   10      F9     835      853.0      834.0
99938   2013     12   19      DL    1223      849.0      847.0
98014   2013     12   17      AA     172      845.0      846.0
95530   2013     12   14      DL    2391      825.0      856.0
182478  2013      4   19      DL    1435      812.0      821.0
246911  2013      6   27      AA    2019      803.0      802.0
152312  2013      3   18      DL    2363      800.0      784.0

In [34]:
# Sort all AA flights to find the top 10 fastest (highest speed) flights.
# Display the following: year,month,day,carrier,flight,orig,dest,distance,air_time,speed (miles per hour)

# Step 1: filter AA flights
aa_flights = flights[flights['carrier'] == 'AA']

# Step 2: create speed (mph)
aa_flights['speed'] = aa_flights['distance'] / (aa_flights['air_time'] / 60)

# Step 3–4: sort + select + top 10
print(aa_flights.sort_values(by='speed', ascending=False)[
    ['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'distance', 'air_time', 'speed']
].head(10))

        year  month  day carrier  flight origin dest  distance  air_time  \
70704   2013     11   17      AA     936    JFK  STT      1623     175.0
87723   2013     12    5      AA    1029    JFK  SJU      1598     173.0
119700  2013      2   10      AA    1613    JFK  SJU      1598     173.0
129686  2013      2   21      AA    1613    JFK  SJU      1598     174.0
87575   2013     12    5      AA      95    JFK  SJU      1598     175.0
144408  2013      3    9      AA    1613    JFK  SJU      1598     176.0
70721   2013     11   17      AA    1357    JFK  SJU      1598     176.0
70335   2013     11   16      AA      95    JFK  SJU      1598     177.0
119477  2013      2   10      AA    1635    JFK  SJU      1598     177.0
119894  2013      2   11      AA     413    JFK  SJU      1598     177.0

             speed
70704   556.457143
87723   554.219653
119700  554.219653
129686  551.034483
87575   547.885714
144408  544.772727
70721   544.772727
70335   541.694915
119477  541.694915
119894  541.694915

/tmp/ipykernel_11272/736180262.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aa_flights['speed'] = aa_flights['distance'] / (aa_flights['air_time'] / 60)

In [35]:
# Find all flights that satisfy the following:
# - From John F. Kennedy Airpot (JFK) or Newark Aiport (EWR) to Seattle-Tacoma Airport (SEA)
# - Carrier is UA, AA, or DL.
# - Dates from 4/1/2013 (inclusive) to 4/3/2013 (inclusive)
# - Scheduled arrival time is before noon.
# - Display the following: year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
# - Sort by year, month, day, sched_arr_time

print(flights[
    (flights['origin'].isin(['JFK', 'EWR'])) &
    (flights['dest'] == 'SEA') &
    (flights['carrier'].isin(['UA', 'AA', 'DL'])) &
    (flights['year'] == 2013) &
    (flights['month'] == 4) &
    (flights['day'].between(1, 3)) &
    (flights['sched_arr_time'] < 1200)
][
    ['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'sched_dep_time', 'sched_arr_time']
].sort_values(by=['year', 'month', 'day', 'sched_arr_time']))

        year  month  day carrier  flight origin dest  sched_dep_time  \
165210  2013      4    1      DL     183    JFK  SEA             745
166180  2013      4    2      DL     183    JFK  SEA             745
167168  2013      4    3      DL     183    JFK  SEA             745

        sched_arr_time
165210            1100
166180            1100
167168            1100